version: 2
executorType: docker
containerInfo:
  - image: kimh/picard-trusty:5740

stages:
  build:

    verbose: true
    parallel: 1
    steps:
      - type: shell
        pwd: /tmp
        command: echo hi

