version: 2
executorType: docker
verbose: true
containerInfo:
  - image: kimh/picard-trusty:5740

stages:
  build:

    parallel: 1
    steps:
      - type: shell
        pwd: /tmp
        command: echo hi
