version: 2
executorType: docker
containerInfo:
  - image: kimh/picard-trusty:5740

stages:
  build:

    #workDir: ~/picard-test

    parallel: 1
    steps:
      #- type: checkout
      - type: shell
        pwd: /tmp
        command: echo hi
