version: 2
jobs:
  build:
    docker:
      - image: kimh/picard-trusty:5740

    working_directory: /tmp/code
    steps:
      - run: rm $(which git)
      - checkout
      - run: ls -la
      - run: echo this is pr foo yo
      - run: cat circle.yml




